on:
   push:
      branches:
         - master
name: "create release on commit"
jobs:
   release-on-push:
      runs-on: ubuntu-latest
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
         - uses: rymndhng/release-on-push-action@master
           with:
            tag_prefix: "v"
            bump_version_scheme: minor
            use_github_release_notes: true
